### ISSUE TITLE
Linking error against libcuda (using GHC 7.8.2)

### ISSUE THREAD

**Issue by svenssonjoel** [tmcdonell/cuda#11]
setup: 
Ubuntu Linux 13.04
CUDA version 5.0 
Driver Version 304.116
hs cuda version cuda-0.5.1.1

Taste of error messages: 
undefined reference to `cuCtxAttach'
undefined reference to `cuCtxDetach'
...

**Comment by tmcdonell** [comment]
I'm closing this because it's been quiet for so long, and the configuration process is now completely rewritten. Please open a new ticket if you still have problems!
