### ISSUE TITLE
Linker errors on Win32 — the `strnlen` is not available

### ISSUE THREAD

**Issue by mwu-tow** [tmcdonell/cuda#22]
Hi,
when compiling a program using cuda, I'm getting linking errors ```undefined reference to `strnlen'```. They are caused by the references to the function in https://github.com/tmcdonell/cuda/blob/master/Foreign/CUDA/Driver/Module.chs

The `strnlen` function is not a part of C language standard. While it is provided by MS Visual Studio runtime and many of the MinGW distributions, it is NOT a part of MinGW distributed along with GHC binaries that has to be used to link the programs.

I have managed to work around the problem by replacing the `strnlen` with `strlen` in the Module.chs — it seems to work, however I'm not sure if this is the right thing to do (are the non-terminated string actually possible there?).

**Comment by tmcdonell** [comment]
Closed by #24.
