### ISSUE TITLE
Warning: Unknown CUDA device compute capability: 5.2

### ISSUE THREAD

**Issue by cpdurham** [tmcdonell/cuda#27]
Getting this warning running a gtx 980, got it running with the nvidia-346 drivers

**Comment by tmcdonell** [comment]
Ah okay, thanks for the heads up! It's just a new kind of device that will need to be put into the analysis tables. From memory, if your specific device isn't found, it'll just proceed as if it were compute 3.0.

**Comment by cpdurham** [comment]
Yeah, I saw the tables, didn't want to want to try to do a fork and mess with the scary numbers there.

I'm finding it interesting than I get a warning message for each call to run1. I would think that the defaultContext call would cache. The only part in the cuda-accelerate I see calling into deviceResources is selectBestDevice.

**Comment by tmcdonell** [comment]
Huh, good catch. That should be fixed.

**Comment by tmcdonell** [comment]
This is now released as cuda-0.6.6.0.
