### ISSUE TITLE
Does not build on GHC 7.10

### ISSUE THREAD

**Issue by yongqli** [tmcdonell/cuda#28]
tmp/cuda-0.6.6.0-11616/cuda-0.6.6.0/dist/dist-sandbox-286213a2/setup/setup.hs:46:28:
    Ambiguous occurrence ‘die’
    It could refer to either ‘Distribution.Simple.Utils.die’,
    imported from ‘Distribution.Simple.Utils’ at
    /tmp/cuda-0.6.6.0-11616/cuda-0.6.6.0/dist/dist-sandbox-286213a2/setup/setup.hs:6:1-32
    or ‘System.Exit.die’,
    imported from ‘System.Exit’ at
    /tmp/cuda-0.6.6.0-11616/cuda-0.6.6.0/dist/dist-sandbox-286213a2/setup/setup.hs:15:1-18

    /tmp/cuda-0.6.6.0-11616/cuda-0.6.6.0/dist/dist-sandbox-286213a2/setup/setup.hs:58:19:
    Ambiguous occurrence ‘die’
    It could refer to either ‘Distribution.Simple.Utils.die’,
    imported from ‘Distribution.Simple.Utils’ at
    /tmp/cuda-0.6.6.0-11616/cuda-0.6.6.0/dist/dist-sandbox-286213a2/setup/setup.hs:6:1-32
    or ‘System.Exit.die’,
    imported from ‘System.Exit’ at
    /tmp/cuda-0.6.6.0-11616/cuda-0.6.6.0/dist/dist-sandbox-286213a2/setup/setup.hs:15:1-18

    /tmp/cuda-0.6.6.0-11616/cuda-0.6.6.0/dist/dist-sandbox-286213a2/setup/setup.hs:94:36:
    Ambiguous occurrence ‘die’
    It could refer to either ‘Distribution.Simple.Utils.die’,
    imported from ‘Distribution.Simple.Utils’ at
    /tmp/cuda-0.6.6.0-11616/cuda-0.6.6.0/dist/dist-sandbox-286213a2/setup/setup.hs:6:1-32
    or ‘System.Exit.die’,
    imported from ‘System.Exit’ at
    /tmp/cuda-0.6.6.0-11616/cuda-0.6.6.0/dist/dist-sandbox-286213a2/setup/setup.hs:15:1-18
    )

**Comment by yongqli** [comment]
`import System.Exit                              hiding (die)` fixed it.

**Comment by tmcdonell** [comment]
Thanks!
