### ISSUE TITLE
FFI calls to Cuda crash on Windows on x64 architecture

### ISSUE THREAD

**Issue by mwu-tow** [tmcdonell/cuda#31]
I should have noticed it earlier. Now the package seamlessly installs on Windows and all would be well… if not the crashes. I did my tests on 32-bit GHC distributions and it worked. However, on 64-bit GHC distributions any program using `cuda` will crash as soon as the first ffi call being made.

Interestingly, the programs work fine when executed by `runghc` or `ghci`. The crash happens only when I generate the `.exe` file and run it.

Repro:
I have a file `Cuda.hs`:
```haskell
import Foreign.CUDA.Driver.Device

main = putStr "Help " >> initialise [] >> putStrLn "me"
```

When calling `runhaskell Cuda.hs` I get `Help me`, when building `ghc Cuda.hs` and calling generated `Cuda.exe` I get `Help` and then crash occurs.

I am still investigating the issue, it looks as if the ffi calls on x64 were somehow broken. I'll try to reduce the problem. I'll write more soon.

**Comment by mwu-tow** [comment]
I've made a minimal repro and reported the problem on GHC bugracker: https://ghc.haskell.org/trac/ghc/ticket/10885

It seems that on 64-bit architecture, GHC cannot properly handle MSVC-generated import libraries.

**Comment by mwu-tow** [comment]
I believe that problem could be worked around by linking the .dll binaries directly (instead of import libraries .lib). Likely I'll check this possibility within a few days.

**Comment by tmcdonell** [comment]
Ah! I hope that this is not a show-stopper for you. I will keep an eye on the ghc issue as well.

**Comment by mwu-tow** [comment]
This is a bug in binutils that are shipped with GHC. It can be worked around by replacing broken binutils with the ones from the linked package: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-binutils-2.25.1-1-any.pkg.tar.xz

Another workaround is making linker to link directly against .dll's instead of MS-style import libraries. I succeeded in building the Cuda library and running some simple programs, however it fails when building larger packages (like `accelerate-examples`) — adding C:\Windows\System32 to libraries directories and circumventing the import libraries apparently breaks some things. 
I hoped that with this approach it would be possible to make a workaround on side of this package (I like when things "just work") but it is not feasible.

We may either ignore the issue for now and wait half an year until the new GHC release fixes the issue or try to detect the problem in the configure phase and make it fail unless the corrected binutils are available. (That way user would get sensible diagnostics when installing package instead of strange-looking crash in the runtime).

@tmcdonell What do you think — should I make configure step fail when generated binaries will crash?

**Comment by tmcdonell** [comment]
If I understand correctly, this bug will manifest in all currently shipping versions of GHC?

In that case, I think that the most important thing is that there are clear instructions somewhere for how to upgrade the broken binutils to fix the problem. Then, we can put a link to the instructions in the description of the package. If the instructions are _very_ short we could even just include it as part of the package description. Otherwise, a wiki page on this repo may be easiest.

Issuing a warning/error and link to the page containing the fix instructions during the build would be good, and especially helpful in cases where the `cuda` package is just pulled in as a dependency (e.g. by `accelerate-cuda`). If it is easy to check the installed version of binutils, do that, but I would also accept just checking for 64-bit GHC < 8.0 (or 7.12, whichever is the next version to contain the fix). If you have time and it is easy to do, this second part would be greatly appreciated, but as I said I think just having the clear instructions on how to fix it is the priority.

**Comment by tmcdonell** [comment]
@mwu-tow I noticed you had a patch which looks to address this, is it ready for a PR? (-;

**Comment by mwu-tow** [comment]
Unfortunately it is not. Sorry for neglecting to answer in this topic. I started work on the patch, then I got discouraged and distracted by other things. 

I want to eventually resume the work and have it merged. I personally have encountered the bug at least twice since then… It's hard to remember to patch `ld.exe` on every machine on every GHC installation (particularly when `stack setup` helps so much in having multiple GHC installations on system). And the crash is really ugly, unless you know what it is, it's very hard to debug. 

One unpleasant part I observed is that GHC installtion comes with two copies of `ld.exe`:
* ghcpath\mingw\bin\ld.exe
* ghcpath\mingw\x86_64-w64-mingw32\bin\ld.exe

The first one is typically found when we try to programatically check the path, eg. by running `stack exec where ld` or, more unfortunately, when using Cabal library to detect `ld` program (as my patch for `Setup.hs` attempted to). 
The second one is the one actually used for linking. I have checked that patching just the second one is enough to fix the issue. I have no idea when the first one is used (if it us used at all) nor why the distribution is built in such way. 

Moreover, if there is some other `ld.exe` available in `PATH` (e.g. because user installed MinGW before installing GHC and added only ghc binaries directory to `PATH`) even more unexpected things can happen — `ld.exe` from `PATH` will be used for… some things (not sure what exactly) and if `ld.exe` is incompatible with the GHC (eg. because of 32/64 bit mismatch) even more absurd, undebugable mess will occur. 

And then I observed that I spent too much time on the issue and other urgent stuff came by.
For now I just wrote a wiki page in my fork: https://github.com/mwu-tow/cuda/wiki/Using-cuda-package-on-Windows so I can direct my coworkers there. I hoped to move it here along with `Setup.hs` fix…

**Comment by tmcdonell** [comment]
ah, this sounds much more complicated than we anticipated. Perhaps we will need to give up on checking this automatically for now, and just include a big warning and a link to your instructions.

One thing to try, does `ghc --info` point to the correct version of `ld` that it uses?

**Comment by mwu-tow** [comment]
Big warning gives us very little. Most of tools, like cabal-install or stack tend to hide any non-error output. I'd really like for it to be a hard failure, forcing user to fix the issue. Otherwise `cuda` will install successfully but every program using it will crash in runtime.

The `ghc --info` shows the first `ld` location, i.e. the one that doesn't need to be patched. As I understand the first one is `ld` used by `ghc` while the second one is `ld` used by MinGW's `gcc`. Why the second one does "the actual linking" — I don't know.

I'm somewhat busy now but I'll try to wrap up these changes and have PR submitted next week. Sorry for the delay.

**Comment by mwu-tow** [comment]
I have it basically done. Within a day or two I'll rebase this against the master and submit PR.

**Comment by tmcdonell** [comment]
Sorry it took me so long to merge in the patches. I have uploaded the new version `cuda-0.7.0.0` to Hackage.

https://hackage.haskell.org/package/cuda-0.7.0.0

Thanks once again for doing all this! (:
