### ISSUE TITLE
getMemInfo raising CUDA Exception: invalid device context

### ISSUE THREAD

**Issue by pmlodawski** [tmcdonell/cuda#34]
Hi! I'm trying to get informationa about availiable memory, but I keep getting this error. Am I missing something?

    module Main where
    import qualified Foreign.CUDA.Driver.Marshal as DMarschal
    import qualified Foreign.CUDA.Driver.Device as DDevice

    main :: IO ()
    main = do
        DDevice.initialise []
        print =<< DMarschal.getMemInfo

error:

    Main.hs: CUDA Exception: invalid device context

**Comment by tmcdonell** [comment]
Although the error provided by CUDA is inscrutable, it is on point: you did not create a device context. Or, put another way, you didn't tell it for which GPU it should return information on available memory. Contexts are associated with a particular device and all operations take place with respect to that context, so you'll need to create one before doing anything.

I've been putting together a basic tutorial on using the driver interface, which you can find as part of the top-level driver module. Hopefully that helps get you up and running, but do let me know if you think it is missing any key steps!

https://github.com/tmcdonell/cuda/blob/master/Foreign/CUDA/Driver.hs

**Comment by pmlodawski** [comment]
Thanks for brief explaination!
