### ISSUE TITLE
Missing -lcuda: Having to add cuda-6.5/lib64/stubs dir to cuda.buildinfo

### ISSUE THREAD

**Issue by mkloczko** [tmcdonell/cuda#35]
Hello!

I've installed both cuda-6.5 and cuda-7.5 for 64 bit Linux using the runfiles from nvidia's website.

This is a minor thing, but I had problems supplying the libcuda.so file. It was hiding in the cuda-x.y/lib64/stubs in cuda.buildinfo. 

It would be nice if this subdirectory could be found automatically, so one could install the whole package from hackage.

**Comment by tmcdonell** [comment]
This is strange that you needed to specify the `stubs` directory. It looks like that is an internal directory that we shouldn't need to worry about...

Which Linux distro are you running? Which version of the CUDA package are you having problems with (i.e. from hackage or github)? I just installed both versions on a Ubuntu 14.04 box with CUDA-7.5 without problems.

**Comment by MKloczko** [comment]
Thank you for your response.

I've forgot to add - I am installing the runfile for Fedora 21 on Fedora 22. The cuda package was from github (version 0.7.0.0)

**Comment by tmcdonell** [comment]
Do you have to add the stubs directory when you use `nvcc` normally? Perhaps build one of  the sample programs from the CUDA SDK and show us the log, so we can see what flags the makefiles used.

**Comment by MKloczko** [comment]
There is no need to add stubs directory when using nvcc. 

The log for compiling volumeRender is:

```
"/usr/local/cuda-7.5"/bin/nvcc -ccbin g++ -I../../common/inc  -m64    -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -o volumeRender.o -c volumeRender.cpp
"/usr/local/cuda-7.5"/bin/nvcc -ccbin g++ -I../../common/inc  -m64    -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -o volumeRender_kernel.o -c volumeRender_kernel.cu
"/usr/local/cuda-7.5"/bin/nvcc -ccbin g++   -m64      -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -o volumeRender volumeRender.o volumeRender_kernel.o  -L../../common/lib/linux/x86_64 -L/usr/lib64/nvidia -lGL -lGLU -lX11 -lglut -lGLEW
mkdir -p ../../bin/x86_64/linux/release
cp volumeRender ../../bin/x86_64/linux/release
```

**Comment by tmcdonell** [comment]
Does your installation happen to include a `pkg-config` file? It might be in `/usr/local/cuda-7.5/lib64/pkgconfig`. If so can you post its contents for me?

Looking at this again, the need to add `-L/usr/lib64/nvidia` is a bit suspicious to me, and adding the stubs dir might have indirectly pointed you to the right place (or perhaps the other way around). The `pkg-config` file might have more information.

**Comment by tmcdonell** [comment]
Closing as inactive.
