### ISSUE TITLE
Cannot build cuda with c2hs-0.26.2 

### ISSUE THREAD

**Issue by mwu-tow** [tmcdonell/cuda#38]
When I have `c2hs` in version 0.26.2 (latest released) I get the following error when building `cuda`:
```
Building cuda-0.6.7.0...
Preprocessing library cuda-0.6.7.0...
c2hs: Errors during expansion of binding hooks:

dist/build/Foreign/CUDA/Runtime/Device.chs.h:6: (column 1) [ERROR]  >>> Illegal use of incomplete type!
  Expected a fully defined structure or union tag; instead found incomplete type.
```

Everything works fine after I downgraded it to 0.26.1. I guess this might be the reason for recent Travis failures.

**Comment by tmcdonell** [comment]
I can't quite figure out what the error was, but luckily this appears to have been fixed in c2hs-0.27.1.
