### ISSUE TITLE
Unknown CUDA device compute capability 6.1

### ISSUE THREAD

**Issue by gordon1992** [tmcdonell/cuda#40]
Hello,

I'm running nVidia 367.27 on Ubuntu 16.04 with CUDA 8.0 RC for my nVidia GTX 1080.

When running accelerate-nofib, I get the following message repeated many times.

*** Warning: Unknown CUDA device compute capability: 6.1
*** Please submit a bug report at https://github.com/tmcdonell/cuda/issues

Looks like this repository just needs updated for the latest Pascal GPUs.

Thanks,
Gordon

**Comment by tmcdonell** [comment]
Thanks for the heads up! I'll add the relevant device information.

**Comment by tmcdonell** [comment]
https://hackage.haskell.org/package/cuda-0.7.5.1
