### ISSUE TITLE
CUDA 8 support [was: Plans to support CUDA 8?]

### ISSUE THREAD

**Issue by alpmestan** [tmcdonell/cuda#42]
Hello,

I recently came back to GPU programming and checked out what was new there. I've [just read](https://devblogs.nvidia.com/parallelforall/cuda-8-features-revealed/) about CUDA 8 but saw that it's not yet supported by this library (not surprising given it's been out for a day =P). Any ongoing plans for supporting it or should I put a patch (that's admittedly quite a big one though I guess) together myself if I ever need CUDA8 features?

Cheers

**Comment by tmcdonell** [comment]
I am currently travelling but will have a look when I get back in a week. Do you have a sense of how large the API change/addition set is? Or, do you know what features you need? Patches are always welcome.

**Comment by alpmestan** [comment]
At a first glance, it would seem the big additions would be FP16/Int8 support and the graph processing API. The former probably isn't too much work (we have the [half](http://hackage.haskell.org/package/half) package after all), but the latter might be. I guess I'll come back to this if I ever need those but I can do without for now, so no hurry =)

**Comment by tmcdonell** [comment]
http://hackage.haskell.org/package/cuda-0.8.0.0

**Comment by alpmestan** [comment]
Great, thanks @tmcdonell :+1:
