### ISSUE TITLE
Compilation fails for CUDA-8 [was: ghc 7.10.3 fail to install]

### ISSUE THREAD

**Issue by acheshkov** [tmcdonell/cuda#44]
`[1 of 1] Compiling Main             ( examples/src/deviceQueryDrv/DeviceQuery.hs, dist/build/nvidia-device-query/nvidia-device-query-tmp/Main.o )

examples/src/deviceQueryDrv/DeviceQuery.hs:85:9:
    Not in scope: data constructor ‘Exclusive’
cabal: Leaving directory '/tmp/cabal-tmp-4620/cuda-0.7.5.0'
World file is already up to date.
cabal: Error: some packages failed to install:
cuda-0.7.5.0 failed during the building phase. The exception was:
ExitFailure 1
`

i can't install package

**Comment by tmcdonell** [comment]
I haven't upgraded it to support CUDA-8 yet. You can downgrade your CUDA installation to 7.5, or try my work-in-progress branch [here](https://github.com/tmcdonell/cuda/tree/feature/8.0).

**Comment by tmcdonell** [comment]
https://hackage.haskell.org/package/cuda-0.7.5.1
