### ISSUE TITLE
Issues with dynamic parallelism?

### ISSUE THREAD

**Issue by roboguy13** [tmcdonell/cuda#49]
I'm trying to use dynamic parallelism on a GPU with compute capability 3.5 (verified by deviceQuery).

If I run a simple CUDA program without dynamic parallelism, it functions fine but if I uncomment the marked line below it gives an error. I've tested it on two machines with two different GPUs and I get an error on both (though the errors are different).

The Haskell code is:

```
  [... More initialization happens here ...]
  cm      <- loadFile "cudabits/cached_mult.ptx"
  ldpcFun <- getFun cm "ldpc"

  (orig_lam_dev, orig_lam_len) <- newListArrayLen $ U.toList $ orig_lam
  result_dev   <- mallocArray orig_lam_len :: IO (DevicePtr IntT)

  launchKernel ldpcFun (1,1,1) (1,1,1) 0 Nothing [VArg mLet, VArg offsets, IArg rowCount, IArg colCount, IArg (fromIntegral maxIterations), VArg orig_lam_dev, IArg (fromIntegral orig_lam_len), VArg result_dev]

  sync

  result <- peekListArray orig_lam_len result_dev

  free result_dev
  free orig_lam_dev
  free mLet
  free offsets

  return $! Just $! U.map toBool $! U.fromList result
```

and the CUDA code is:

```
extern "C" __global__ void f() {
}

extern "C" __global__ void ldpc(double* mLet, double* offsets, int rowCount, int colCount, int maxIterations, double* orig_lam, int orig_lam_len, int* result) {

  f<<<1, 1>>>();  // **** If I comment this line out, it runs fine ****

  for (int i = 0; i < orig_lam_len; ++i) {
    result[i] = orig_lam[i] > 0;
  }
}
```

I'm compiling the CUDA code with

```
nvcc cached_mult.cu --compiler-options -std=c++98 -arch=sm_35 -gencode=arch=compute_35,code=sm_35 -rdc=true -lcudadevrt -ptx
```

It might be worth pointing out that, on one machine, I have an unsupported version of GCC (which is why I have the `--compiler-options` flag, to work around that). On the other machine, though, I do have a supported version of GCC (4.8.5).

The machine with the unsupported version of GCC has a GeForce GT 710B which has the GK208 architecture. The error on this machine is `CUDA_ERROR_NO_BINARY_FOR_GPU (error 209) due to "no kernel image is available for execution on the device" on CUDA API call to cuModuleLoad.`

The other machine (with GCC 4.8.5) has a K80. On this machine, the error is ` CUDA_ERROR_INVALID_PTX (error 218) due to "a PTX JIT compilation failed" on CUDA API call to cuModuleLoad.` I've also tried adjusting the compilation flags to use the 3.7 capability of the K80, just in case, but it doesn't seem to affect anything.

In both cases, commenting out the line marked in the CUDA code lets it run without error.

Also, if I just add a `main` with a simple call to `ldpc` to the CUDA code and compile it directly to an executable, that executable seems to run without an error.

Am I missing an option or flag?

**Comment by tmcdonell** [comment]
That is a good question. I have never actually tried out the dynamic parallelism feature, so I'm not sure off hand how to set it up. Let me find a compatible GPU and try it out...

**Comment by roboguy13** [comment]
It looks like if I change it to compile to a `.cubin` instead of `.ptx` (and I load that), it gives another different error: `CUDA Exception: device kernel image is invalid`. This occurs on the machine with the incompatible GCC version that I'm using the workaround for (at least. I haven't tried the other ones yet).

**Comment by tmcdonell** [comment]
Sorry, this fell off the radar.

I was able to do this by following [this SO post](https://stackoverflow.com/questions/27829906/cuda-dynamic-parallelism-with-driver-api). Change your `loadFile` line with something like the following instead:

```haskell
import System.FilePath

import Foreign.CUDA.Path
import Foreign.CUDA.Driver.Module.Link as Linker

  -- same setup as before

  ls <- Linker.create []
  addFile ls "cudabits/cached_mult.ptx" Linker.PTX []
  addFile ls (cudaLibraryPath </> "libcudadevrt.a") Linker.Library []
  cm <- Linker.complete ls
  
  -- everything else
```

**Comment by tmcdonell** [comment]
I think this is resolved; please reopen if you still have problems.
