### ISSUE TITLE
Structure of nvidia-cuda-toolkit seems to have changed in Ubuntu 18.04

### ISSUE THREAD

**Issue by fabricatedmath** [tmcdonell/cuda#54]
Just a heads up, 

Tried to install the cuda package on Ubuntu 18.04 ahead of it's release. If you leave it to install with no CUDA_PATH set, it finds nvcc at /usr/bin/nvcc, then goes up a couple levels and can't find /usr/lib64. If I set CUDA_PATH to /usr/lib/cuda I get:

```
    checking for environment variable CUDA_PATH
    Path rejected: /usr/lib/cuda
    Does not exist: /usr/lib/cuda/include/cuda.h
    checking for nvcc compiler executable in PATH
    Path accepted: /usr
    Found CUDA toolkit at: /usr
    CallStack (from HasCallStack):
      die', called at /tmp/stack770/cuda-0.9.0.3/Setup.hs:149:26 in main:Main
    setup: Could not find path: ["/usr/lib64"]
```
(include and lib64 are empty, copied to /usr/include/ and /usr/lib/x86_64-linux-gnu/ instead)

Was the first time I installed 'nvidia-cuda-toolkit' from apt-get in a long time due to its lag in release (right now its current at 9.1), not sure if this structure changed just in 18.04.

I did try creating /usr/lib64 for fun, cuda compiled, but accelerate-llvm-ptx died not being able to find the nvvm directory and libdevice (nvvm/libdevice being located in /usr/lib/cuda), also strange because I thought nvvm was default off?

**Comment by tmcdonell** [comment]
I think this is fixed and can be closed with AccelerateHS/accelerate#444
