### ISSUE TITLE
Compile issues for Cabal 2?

### ISSUE THREAD

**Issue by AlexMouton** [tmcdonell/cuda#63]
Hi Trevor
Trying to bring my pet project up to date im seeing:

cuda                  > /tmp/stack-19b9ea176767e51e/cuda-0.10.1.0/Setup.hs:199:29: error:
cuda                  >     • Couldn't match expected type ‘PerCompilerFlavor [String]’
cuda                  >                   with actual type ‘[(CompilerFlavor, [[Char]])]’

as an aside something else is reporting:
WARNING: Ignoring cuda's bounds on Cabal (>=1.24 && <3); using Cabal-3.0.1.0.
but the cabal version branching around this error  is #if MIN_VERSION_Cabal(3,0,0) ?

Full error text:

cuda                  > /tmp/stack-19b9ea176767e51e/cuda-0.10.1.0/Setup.hs:199:29: error:
cuda                  >     • Couldn't match expected type ‘PerCompilerFlavor [String]’
cuda                  >                   with actual type ‘[(CompilerFlavor, [[Char]])]’
cuda                  >     • In the ‘options’ field of a record
cuda                  >       In the second argument of ‘($)’, namely
cuda                  >         ‘emptyBuildInfo
cuda                  >            {ccOptions = ccOptions', ldOptions = ldOptions',
cuda                  >             extraLibs = extraLibs', extraGHCiLibs = extraGHCiLibs',
cuda                  >             extraLibDirs = extraLibDirs', frameworks = frameworks',
cuda                  >             extraFrameworkDirs = frameworkDirs',
cuda                  >             options = [(GHC, ghcOptions) | os /= Windows],
cuda                  >             customFieldsBI = [c2hsExtraOptions]}’
cuda                  >       In a stmt of a 'do' block:
cuda                  >         buildInfo' <- addSystemSpecificOptions
cuda                  >                         $ emptyBuildInfo
cuda                  >                             {ccOptions = ccOptions', ldOptions = ldOptions',
cuda                  >                              extraLibs = extraLibs', extraGHCiLibs = extraGHCiLibs',
cuda                  >                              extraLibDirs = extraLibDirs', frameworks = frameworks',
cuda                  >                              extraFrameworkDirs = frameworkDirs',
cuda                  >                              options = [(GHC, ghcOptions) | os /= Windows],
cuda                  >                              customFieldsBI = [c2hsExtraOptions]}
cuda                  >     |
cuda                  > 199 |     , options             = [(GHC, ghcOptions) | os /= Windows]
cuda                  >     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by tmcdonell** [comment]
Hi Alex,

Which version of GHC were you trying to build with? I just tried with the `stack-8.2.yaml` config and that worked for me (Cabal-2.0.1.0) so I'll need to dig a bit deeper to figure out what is going wrong.

**Comment by AlexMouton** [comment]
Closing this one. Who knows what my issue was. Thanks for looking.
