### ISSUE TITLE
 Cannot find a definition for `cuDevicePrimaryCtxRelease' in the header file.

### ISSUE THREAD

**Issue by schnecki** [tmcdonell/cuda#66]
Hi, 

I cannot install cuda via stack: 

    [09:02:44 schnecki grenade]$ stack build cuda
    cuda> configure
    cuda> [1 of 2] Compiling Main             ( /tmp/stack-54c629f074650108/cuda-0.10.2.0/Setup.hs, /tmp/stack-54c629f074650108/cuda-0.10.2.0/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0/setup/Main.o )
    cuda> [2 of 2] Compiling StackSetupShim   ( /home/schnecki/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack-54c629f074650108/cuda-0.10.2.0/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0/setup/StackSetupShim.o )
    cuda> Linking /tmp/stack-54c629f074650108/cuda-0.10.2.0/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0/setup/setup ...
    cuda> Configuring cuda-0.10.2.0...
    cuda> Found CUDA toolkit at: /opt/cuda
    cuda> Storing parameters to cuda.buildinfo.generated
    cuda> Using build information from 'cuda.buildinfo.generated'.
    cuda> Provide a 'cuda.buildinfo' file to override this behaviour.
    cuda> build
    cuda> Using build information from 'cuda.buildinfo.generated'.
    cuda> Provide a 'cuda.buildinfo' file to override this behaviour.
    cuda> Preprocessing library for cuda-0.10.2.0..
    cuda> c2hs: Errors during expansion of binding hooks:
    cuda> 
    cuda> src/Foreign/CUDA/Driver/Context/Primary.chs:139: (column 15) [ERROR]  >>> Unknown identifier!
    cuda>   Cannot find a definition for `cuDevicePrimaryCtxRelease' in the header file.
    cuda> src/Foreign/CUDA/Driver/Context/Primary.chs:114: (column 15) [ERROR]  >>> Unknown identifier!
    cuda>   Cannot find a definition for `cuDevicePrimaryCtxReset' in the header file.
    cuda> src/Foreign/CUDA/Driver/Context/Primary.chs:91: (column 15) [ERROR]  >>> Unknown identifier!
    cuda>   Cannot find a definition for `cuDevicePrimaryCtxSetFlags' in the header file.
    cuda> 
    
    --  While building package cuda-0.10.2.0 (scroll up to its section to see the error) using:
          /tmp/stack-54c629f074650108/cuda-0.10.2.0/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build --ghc-options " -fdiagnostics-color=always"
        Process exited with code: ExitFailure 1

As c2hs is erroring, I suppose there is an error in the code. Or is this a issue with my CUDA installation? I installed cuda and could compile the examples. The result of the deviceQuery is:

    [09:08:19 schnecki ~]$ /opt/cuda/samples/1_Utilities/deviceQuery/deviceQuery 
    /opt/cuda/samples/1_Utilities/deviceQuery/deviceQuery Starting...
    
     CUDA Device Query (Runtime API) version (CUDART static linking)
    
    Detected 1 CUDA Capable device(s)
    
    Device 0: "GeForce GTX 1050 Ti"
      CUDA Driver Version / Runtime Version          11.1 / 10.1
      CUDA Capability Major/Minor version number:    6.1
      Total amount of global memory:                 4040 MBytes (4236312576 bytes)
      ( 6) Multiprocessors, (128) CUDA Cores/MP:     768 CUDA Cores
      GPU Max Clock rate:                            1620 MHz (1.62 GHz)
      Memory Clock rate:                             3504 Mhz
      Memory Bus Width:                              128-bit
      L2 Cache Size:                                 1048576 bytes
      Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
      Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
      Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
      Total amount of constant memory:               65536 bytes
      Total amount of shared memory per block:       49152 bytes
      Total number of registers available per block: 65536
      Warp size:                                     32
      Maximum number of threads per multiprocessor:  2048
      Maximum number of threads per block:           1024
      Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
      Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
      Maximum memory pitch:                          2147483647 bytes
      Texture alignment:                             512 bytes
      Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
      Run time limit on kernels:                     Yes
      Integrated GPU sharing Host Memory:            No
      Support host page-locked memory mapping:       Yes
      Alignment requirement for Surfaces:            Yes
      Device has ECC support:                        Disabled
      Device supports Unified Addressing (UVA):      Yes
      Device supports Compute Preemption:            Yes
      Supports Cooperative Kernel Launch:            Yes
      Supports MultiDevice Co-op Kernel Launch:      Yes
      Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
      Compute Mode:
         < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
    
    deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.1, CUDA Runtime Version = 10.1, NumDevs = 1
    Result = PASS

Edit: I am on ArchLinux. I saw some earlier issue (https://github.com/tmcdonell/cuda/issues/57). Building from github did not work for me. I guess there were more breaking changes?

**Comment by schnecki** [comment]
Ok I installed cuda-10.2 from AUR and it works. 

    yay -S cuda-10.2 

Closing the issue.

**Comment by tmcdonell** [comment]
Ah, sorry for the late response. Yes I haven't had a chance to look into CUDA-11.x support yet, sorry! >.<

**Comment by schnecki** [comment]
No worries, it works with cuda-10.2. Thx for the reply
