### ISSUE TITLE
CUDA 11.3 compatibility

### ISSUE THREAD

**Issue by Abastro** [tmcdonell/cuda#68]
I tried to run accelerate library to run with CUDA, but the following error happened.
```
src/Foreign/CUDA/Driver/Context/Primary.chs:139: (column 15) [ERROR]  >>> Unknown identifier!
  Cannot find a definition for `cuDevicePrimaryCtxRelease' in the header file.
src/Foreign/CUDA/Driver/Context/Primary.chs:114: (column 15) [ERROR]  >>> Unknown identifier!
  Cannot find a definition for `cuDevicePrimaryCtxReset' in the header file.
src/Foreign/CUDA/Driver/Context/Primary.chs:91: (column 15) [ERROR]  >>> Unknown identifier!
  Cannot find a definition for `cuDevicePrimaryCtxSetFlags' in the header file.
```
It seems like there is a problem with CUDA-11.3, could you introduce the compatibility? I cannot downgrade my cuda as that would break other dependencies.

**Comment by tmcdonell** [comment]
Hi @Abastro! Sorry I haven't had time to work on this for a while, I'll try and look into it in the coming weeks >.<

**Comment by Abastro** [comment]
Thanks! Glad to see this project being alive!

**Comment by Abastro** [comment]
While it's being worked on, I can downgrade CUDA to 10.2 (Turns out my other utility does not support CUDA 11.3 either)

**Comment by tmcdonell** [comment]
I forgot to close this issue, but this should work with up to CUDA-11.8.
Now to open an issue for the CUDA-12 series...
