### ISSUE TITLE
Build failure w/ cuda-12.2: parsing error in cuda.h

### ISSUE THREAD

**Issue by leftaroundabout** [tmcdonell/cuda#78]
This is using [the unmerged PR](https://github.com/noahmartinwilliams/cuda/tree/release/0.12.2.0) version that addresses v0.12.2, but the error is actually the same on the `master` version.

Ubuntu 22.04, [cabal 3.6.2](https://hackage.haskell.org/package/cabal-install-3.6.2.0), [GHC 9.2.7](https://www.haskell.org/ghc/download_ghc_9_2_7.html), [c2hs 0.28.8](https://hackage.haskell.org/package/c2hs-0.28.8).
```
Configuring cuda-0.12.2.0...
Found CUDA toolkit at: /usr/local/cuda-12.2 (set CUDA_PATH to override this)
Storing parameters to cuda.buildinfo.generated
Using build information from 'cuda.buildinfo.generated'.
Provide a 'cuda.buildinfo' file to override this behaviour.
Using build information from 'cuda.buildinfo.generated'.
Provide a 'cuda.buildinfo' file to override this behaviour.
Preprocessing library for cuda-0.12.2.0..
c2hs: C header contains errors:

/usr/local/cuda-12.2/include/cuda.h:2930: (column 5) [ERROR]  >>> Syntax error !
  The symbol `_Alignas' does not fit here.

cabal: Failed to build cuda-0.12.2.0
```
It appears like `_Alignas` is a macro which is available when compiling with a C compiler, but `c2hs` is not aware of it.

**Comment by noahmartinwilliams** [comment]
Yes, that's why I made a fork of the language-c library and added support for _Alignas. I did a pull request on that repo but I don't think the maintainer accepted it yet. You'll need that, and a version of c2hs which uses my version of language-c in order to compile this. Sorry, I should have mentioned that.

**Comment by leftaroundabout** [comment]
@noahmartinwilliams right, https://github.com/visq/language-c/pull/94 seems to fix this issue.

**Comment by noahmartinwilliams** [comment]
@leftaroundabout , What are the new errors?

**Comment by leftaroundabout** [comment]
@noahmartinwilliams I think it is completely unrelated to this issue. The error is
```
undefined symbol: _ZSt7nothrow
```
This happens specifically when I'm running Template Haskell splices while depending on `cublas` (regardless of whether I actually use anything the `cublas` package exports).
It does not seem to happen when I only depend on `cuda`, nor when compiling a TH-free program with `cublas` and it certainly hasn't to do with C headers, so I'm closing this here.
